<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[t1t2 and listener and externaldp Started Execution]]>
    </line>
    <line>
      <![CDATA[username entered:u1]]>
    </line>
    <line>
      <![CDATA[password entered:p1]]>
    </line>
    <line>
      <![CDATA[Testcase1is fail]]>
    </line>
    <line>
      <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> TEst case failed:</a>Testcase1]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> <img height = 200 width =200 src ="C:\Users\DSC_0701.jpg"> </img></a>Testcase1]]>
    </line>
    <line>
      <![CDATA[username entered:u2]]>
    </line>
    <line>
      <![CDATA[password entered:p2]]>
    </line>
    <line>
      <![CDATA[Testcase1is fail]]>
    </line>
    <line>
      <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> TEst case failed:</a>Testcase1]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> <img height = 200 width =200 src ="C:\Users\DSC_0701.jpg"> </img></a>Testcase1]]>
    </line>
    <line>
      <![CDATA[Testcase2is pass]]>
    </line>
    <line>
      <![CDATA[Testcase2is pass]]>
    </line>
  </reporter-output>
  <suite started-at="2020-05-05T00:43:30 IST" name="External dp" finished-at="2020-05-05T00:43:30 IST" duration-ms="352">
    <groups>
    </groups>
    <test started-at="2020-05-05T00:43:30 IST" name="t1t2 and listener and externaldp" finished-at="2020-05-05T00:43:30 IST" duration-ms="352">
      <class name="Testlearn.t1t2">
        <test-method signature="Testcase1(java.lang.String, java.lang.String)[pri:0, instance:Testlearn.t1t2@79ca92b9]" started-at="2020-05-05T00:43:30 IST" name="Testcase1" data-provider="extdp" finished-at="2020-05-05T00:43:30 IST" duration-ms="75" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[u1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[p1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at Testlearn.t1t2.Testcase1(t1t2.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[username entered:u1]]>
            </line>
            <line>
              <![CDATA[password entered:p1]]>
            </line>
            <line>
              <![CDATA[Testcase1is fail]]>
            </line>
            <line>
              <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> TEst case failed:</a>Testcase1]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> <img height = 200 width =200 src ="C:\Users\DSC_0701.jpg"> </img></a>Testcase1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testcase1 -->
        <test-method signature="Testcase1(java.lang.String, java.lang.String)[pri:0, instance:Testlearn.t1t2@79ca92b9]" started-at="2020-05-05T00:43:30 IST" name="Testcase1" data-provider="extdp" finished-at="2020-05-05T00:43:30 IST" duration-ms="24" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[u2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[p2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at Testlearn.t1t2.Testcase1(t1t2.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[username entered:u2]]>
            </line>
            <line>
              <![CDATA[password entered:p2]]>
            </line>
            <line>
              <![CDATA[Testcase1is fail]]>
            </line>
            <line>
              <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> TEst case failed:</a>Testcase1]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href ="C:\Users\DSC_0701.jpg"target="_blank"> <img height = 200 width =200 src ="C:\Users\DSC_0701.jpg"> </img></a>Testcase1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testcase1 -->
        <test-method signature="Testcase2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Testlearn.t1t2@79ca92b9]" started-at="2020-05-05T00:43:30 IST" name="Testcase2" data-provider="extdp" finished-at="2020-05-05T00:43:30 IST" duration-ms="11" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[u1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[p1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[e1]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Testcase2is pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testcase2 -->
        <test-method signature="Testcase2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Testlearn.t1t2@79ca92b9]" started-at="2020-05-05T00:43:30 IST" name="Testcase2" data-provider="extdp" finished-at="2020-05-05T00:43:30 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[u2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[p2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[e2]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Testcase2is pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testcase2 -->
      </class> <!-- Testlearn.t1t2 -->
    </test> <!-- t1t2 and listener and externaldp -->
  </suite> <!-- External dp -->
</testng-results>
